& "$PSScriptRoot\RemovePackages.ps1"
& "$PSScriptRoot\RemoveCapabilities.ps1"
& "$PSScriptRoot\RemoveFeatures.ps1"
& "$PSScriptRoot\RemoveOneDrive.ps1" *>> "$PSScriptRoot\..\Logs\RemoveOneDrive.log"
& "$PSScriptRoot\RemoveEdge.ps1" *>> "$PSScriptRoot\..\Logs\RemoveEdge.log"
